# Generated by Django 4.2.6 on 2023-10-13 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FrameworkModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='название')),
                ('language', models.CharField(max_length=200, verbose_name='язык программирования')),
            ],
            options={
                'verbose_name': 'фреймворк',
                'verbose_name_plural': 'фреймворки',
            },
        ),
    ]
